export function calculatePanels(
  annualDemandKwh,
  activePanel,
  efficiencyPercent = 70.5
) {
  const PSH_DAILY = 4.5;
  const DAYS_IN_YEAR = 365;

  const efficiency = efficiencyPercent / 100;

  // Energy generated by one panel per year
  const panelPowerKw = activePanel.powerW / 1000;

  const annualEnergyPerPanel =
    panelPowerKw *
    PSH_DAILY *
    DAYS_IN_YEAR *
    efficiency;

  // Required panel count
  const requiredPanels = Math.ceil(
    annualDemandKwh / annualEnergyPerPanel
  );

  // Total site area
  const totalAreaM2 =
    requiredPanels * activePanel.areaM2;

  // Total DC installed capacity
  const totalInstalledKw =
    (requiredPanels * activePanel.powerW) /
    1000;

  // Number of 10m x 10m reference blocks
  const equivalentSquares =
    totalAreaM2 / 100;

  return {
    panels: requiredPanels || 0,
    area: totalAreaM2.toFixed(2),
    capacity: totalInstalledKw.toFixed(2),
    squares: equivalentSquares.toFixed(1),
    efficiency: efficiencyPercent
  };
}